const dataSmall = [
  {
    id: 1,
    subId: 5,
    name: "img1",
    img: "../pic/main1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale!",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
  },
  {
    name: "img1",
    img: "../pic/main2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale!",
    similar: "tshirt",
    usPrice: "$9.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
  },
  {
    name: "img2",
    img: "../pic/main3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale!",
    similar: "tshirt",
    usPrice: "$7.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
  },
  {
    name: "img4",
    img: "../pic/main4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale!",
    similar: "tshirt",
    usPrice: "$5.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
  },
  // end info1
  {
    id: 5,
    subId: 22,
    name: "img2",
    img: "../pic/menn2.avif",
    class: "img2",
    categoies: "Khmer New Year Sale1",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 6,
    // subId: 22,
    name: "img2",
    img: "../pic/submen1.avif",
    class: "img2",
    categoies: "Khmer New Year Sale1",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 7,
    // subId: 22,
    name: "img2",
    img: "../pic/submen2.avif",
    class: "img2",
    categoies: "Khmer New Year Sale1",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 8,
    // subId: 22,
    name: "img2",
    img: "../pic/submen3.avif",
    class: "img2",
    categoies: "Khmer New Year Sale1",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 22,
    subId: 5,
    name: "img2",
    img: "../pic/submenn2.avif",
    class: "img2",
    categoies: "Khmer New Year Sale5",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 10,
    // subId: 5,
    name: "img1",
    img: "../pic/submenn4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale5",
    usPrice: "$20.99",
    usPriceoff: "$30.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 11,
    // subId: 5,
    name: "img1",
    img: "../pic/submenn3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale5",
    usPrice: "$40.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 23,
    // subId: 5,
    name: "img1",
    img: "../pic/submenn1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale5",
    usPrice: "$40.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 12,
    subId: 17,
    name: "img1",
    img: "../pic/submenn6.avif",
    class: "img1",
    categoies: "Khmer New Year Sale3",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 13,
    // subId: 17,
    name: "img1",
    img: "../pic/submenn6-1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale3",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 14,
    // subId: 17,
    name: "img1",
    img: "../pic/submenn6-2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale3",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 15,
    // subId: 17,
    name: "img1",
    img: "../pic/submenn6-3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale3",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 16,
    // subId: 17,
    name: "img1",
    img: "../pic/submenn6-4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale3",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 17,
    subId: 13,
    name: "img1",
    img: "../pic/submenn5.avif",
    class: "img1",
    categoies: "Khmer New Year Sale4",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 18,
    // subId: 13,
    name: "img1",
    img: "../pic/submenn7-1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale4",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 19,
    // subId: 13,
    name: "img1",
    img: "../pic/submenn7-2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale4",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 20,
    // subId: 13,
    name: "img1",
    img: "../pic/submenn7-3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale4",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 21,
    // subId: 13,
    name: "img1",
    img: "../pic/submenn7-4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale4",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 24,
    subId: 40,
    name: "img1",
    img: "../pic/submenn8.avif",
    class: "img1",
    categoies: "Khmer New Year Sale6",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 25,
    // subId: 13,
    name: "img1",
    img: "../pic/submenn8-1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale6",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 26,
    // subId: 13,
    name: "img1",
    img: "../pic/submen8-2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale6",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 27,
    // subId: 13,
    name: "img1",
    img: "../pic/submenn8-3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale6",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 36,
    subId: 13,
    name: "img1",
    img: "../pic/submenn9.avif",
    class: "img1",
    categoies: "Khmer New Year Sale7",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 37,
    // subId: 13,
    name: "img1",
    img: "../pic/submenn9-1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale7",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 38,
    // subId: 13,
    name: "img1",
    img: "../pic/submenn9-2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale7",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 39,
    // subId: 13,
    name: "img1",
    img: "../pic/submen9-3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale7",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 40,
    subId: 24,
    name: "img1",
    img: "../pic/submenn10.avif",
    class: "img1",
    categoies: "Khmer New Year Sale8",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 41,
    // subId: 24,
    name: "img1",
    img: "../pic/submenn10-1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale8",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 42,
    // subId: 24,
    name: "img1",
    img: "../pic/submenn10-2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale8",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 43,
    // subId: 24,
    name: "img1",
    img: "../pic/submenn10-3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale8",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 44,
    // subId: 24,
    name: "img1",
    img: "../pic/submenn10-3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale8",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 45,
    // subId: 24,
    name: "img1",
    img: "../pic/submenn10-4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale8",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied CropTop",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 51,
    subId: 17,
    name: "img1",
    img: "../pic/track.avif",
    class: "img1",
    categoies: "Khmer New Year Sale9",
    usPrice: "$50.99",
    usPriceoff: "$70.95",
    Priceoff: "-40%",
    typeOfShirt: "Tracksuits",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 52,
    // subId: 24,
    name: "img1",
    img: "../pic/subtrack1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale9",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Tracksuits",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 53,
    // subId: 24,
    name: "img1",
    img: "../pic/subtrack2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale9",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Tracksuits",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 54,
    // subId: 24,
    name: "img1",
    img: "../pic/subtrack3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale9",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Tracksuits",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 55,
    // subId: 24,
    name: "img1",
    img: "../pic/subtrack4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale9",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Tracksuits",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 56,
    subId: 1,
    name: "img1",
    img: "../pic/tshirtmen1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale10",
    usPrice: "$60.99",
    usPriceoff: "$80.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 57,
    // subId: 1,
    name: "img1",
    img: "../pic/subtshirtmen3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale10",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 58,
    // subId: 1,
    name: "img1",
    img: "../pic/subtshirtmen4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale10",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 59,
    // subId: 1,
    name: "img1",
    img: "../pic/subtshirtmen2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale10",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 60,
    subId: 40,
    name: "img1",
    img: "../pic/jacketmen1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale11",
    usPrice: "$70.99",
    usPriceoff: "$90.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 61,
    // subId: 40,
    name: "img1",
    img: "../pic/subjacketmen2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale11",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 62,
    // subId: 40,
    name: "img1",
    img: "../pic/subjacketmen3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale11",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 63,
    // subId: 40,
    name: "img1",
    img: "../pic/subjacketmen4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale11",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 64,
    subId: 22,
    name: "img1",
    img: "../pic/subpolomen1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale13",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 65,
    // subId: 40,
    name: "img1",
    img: "../pic/subpolomen2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale13",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 66,
    // subId: 40,
    name: "img1",
    img: "../pic/subpolomen3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale13",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 67,
    // subId: 40,
    name: "img1",
    img: "../pic/subpolormen4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale13",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 68,
    subId: 22,
    name: "img1",
    img: "../pic/subpolomen2-3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale14",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 69,
    // subId: 40,
    name: "img1",
    img: "../pic/subpolomen2-1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale14",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 70,
    // subId: 40,
    name: "img1",
    img: "../pic/subpolomen2-2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale14",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 71,
    // subId: 40,
    name: "img1",
    img: "../pic/subpolomen2-4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale14",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 72,
    subId: 22,
    name: "img1",
    img: "../pic/subpolomen3-3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale15",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 73,
    // subId: 40,
    name: "img1",
    img: "../pic/polomen3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale15",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 74,
    // subId: 40,
    name: "img1",
    img: "../pic/subpolomen3-1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale15",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 75,
    // subId: 40,
    name: "img1",
    img: "../pic/subpolomen3-2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale15",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 76,
    subId: 40,
    name: "img1",
    img: "../pic/pants2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale16",
    usPrice: "$40.99",
    usPriceoff: "$60.95",
    Priceoff: "-40%",
    typeOfShirt: "Pants And Tights",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 77,
    // subId: 40,
    name: "img1",
    img: "../pic/subpants2-1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale16",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 78,
    // subId: 40,
    name: "img1",
    img: "../pic/subpants2-2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale16",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 79,
    // subId: 40,
    name: "img1",
    img: "../pic/subpants2-3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale16",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 80,
    subId: 24,
    name: "img1",
    img: "../pic/pants1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale17",
    usPrice: "$18.99",
    usPriceoff: "$10.95",
    Priceoff: "-40%",
    typeOfShirt: "Pants And Tights",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 81,
    subId: 24,
    name: "img1",
    img: "../pic/subpants2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale17",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Pants And Tights",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 82,
    name: "img1",
    img: "../pic/subpants3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale17",
    usPrice: "$20.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Pants And Tights",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 83,
    name: "img1",
    img: "../pic/subpants1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale17",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Pants And Tights",
    MaxQuantity: 50,
    similar: "top",
  },
  // women
  {
    id: 84,
    subId: 85,
    name: "img1",
    img: "../pic/womentshirt1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale18",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subwomentshirt3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale18",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subtshirtwomen2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale18",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subwomentshirt4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale18",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 85,
    subId: 84,
    name: "img1",
    img: "../pic/womentshirt2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale19",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied Jersey",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subwomentshirt2-1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale19",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied Jersey",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subwomentshirt2-2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale19",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied Jersey",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subwomentshirt2-3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale19",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied Jersey",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subwomentshirt2-4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale19",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied Jersey",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 86,
    subId: 84,
    name: "img1",
    img: "../pic/hoddiewomen1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale20",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Hoodie",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subhoodiewowmen1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale20",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied Jersey",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subhoodiewomen2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale20",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied Jersey",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subhoodiewomen3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale20",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied Jersey",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subhoodiewomen4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale20",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied Jersey",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 87,
    subId: 84,
    name: "img1",
    img: "../pic/skirt1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale21",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Skirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subskirt1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale21",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied Jersey",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subskirt2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale21",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied Jersey",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subskirt3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale21",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied Jersey",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subskirt4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale21",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied Jersey",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 88,
    subId: 84,
    name: "img1",
    img: "../pic/womenpants1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale22",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Pants And Tights",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subwomenpants1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale22",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Pants And Tights",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subwomenpants2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale22",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Pants And Tights",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subwomenpants3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale22",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Pants And Tights",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subwomenpants4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale22",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Pants And Tights",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 89,
    subId: 84,
    name: "img1",
    img: "../pic/womenshort1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale24",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "short",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subwomenshort2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale24",
    usPrice: "$20.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Pants And Tights",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subwomenshort3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale24",
    usPrice: "$20.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Pants And Tights",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subwomenshort4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale24",
    usPrice: "$20.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Pants And Tights",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subwomenshort1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale24",
    usPrice: "$20.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Pants And Tights",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 90,
    subId: 84,
    name: "img1",
    img: "../pic/fleecec1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale23",
    usPrice: "$40.99",
    usPriceoff: "$80.95",
    Priceoff: "-40%",
    typeOfShirt: "fleece",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subfleece2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale23",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Pants And Tights",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subfleece1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale23",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Pants And Tights",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subfleece2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale23",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Pants And Tights",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subfleece3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale23",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Pants And Tights",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subfleece4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale23",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Pants And Tights",
    MaxQuantity: 50,
    similar: "top",
  },
  // legging
  {
    id: 91,
    subId: 84,
    name: "img1",
    img: "../pic/leg1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale26",
    usPrice: "$20.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "fleece",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subleg1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale26",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Legging",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subleg2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale26",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Legging",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subleg3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale26",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Legging",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subleg4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale26",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Legging",
    MaxQuantity: 50,
    similar: "top",
  },
  // jacket

  // Recent Product
  {
    id: 500,
    name: "Tatum 3",
    img: "../pic/jorden2.avif",
    categoies: "Khmer New Year Sale27",
    usPrice: "$20.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Tatum 3",
    img: "../pic/subjorden2-1.avif",
    categoies: "Khmer New Year Sale27",
    usPrice: "$125.00",
    usPriceoff: "$$235.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Tatum 3",
    img: "../pic/subjorden2-2.avif",
    categoies: "Khmer New Year Sale27",
    usPrice: "$125.00",
    usPriceoff: "$$235.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Tatum 3",
    img: "../pic/subjorden2-3.avif",
    categoies: "Khmer New Year Sale27",
    usPrice: "$125.00",
    usPriceoff: "$$235.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Tatum 3",
    img: "../pic/subjorden2-4.avif",
    categoies: "Khmer New Year Sale27",
    usPrice: "$125.00",
    usPriceoff: "$$235.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },

  {
    id: 501,
    subId: 500,
    name: "Air Jordan 5 Retro",
    price: "223$",
    img: "../pic/jorden1.avif",
    categoies: "Khmer New Year Sale501",
    usPrice: "$20.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "jordan",
    MaxQuantity: 50,
    similar: "top",
  },

  {
    name: "Air Jordan 5 Retro",
    price: "223$",
    img: "../pic/subjorden1.avif",
    categoies: "Khmer New Year Sale501",
    usPrice: "$223.00",
    usPriceoff: "$$235.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 5 Retro",
    price: "223$",
    img: "../pic/subjorden2.avif",
    categoies: "Khmer New Year Sale501",
    usPrice: "$223.00",
    usPriceoff: "$$235.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 5 Retro",
    price: "223$",
    img: "../pic/subjorden3.avif",
    categoies: "Khmer New Year Sale501",
    usPrice: "$223.00",
    usPriceoff: "$$235.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 5 Retro",
    price: "223$",
    img: "../pic/subjorden4.avif",
    categoies: "Khmer New Year Sale501",
    usPrice: "$223.00",
    usPriceoff: "$$235.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },

  {
    id: 502,
    subId: 501,
    name: "Air Jordan 5 Retro",
    price: "223$",
    img: "../pic/jorden3.avif",
    categoies: "Khmer New Year Sale502",
    usPrice: "$20.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 5 Retro",
    img: "../pic/subjorden3-1.avif",
    categoies: "Khmer New Year Sale502",
    usPrice: "$140.00",
    usPriceoff: "$$195.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 5 Retro",
    img: "../pic/subjorden3-2.avif",
    categoies: "Khmer New Year Sale502",
    usPrice: "$140.00",
    usPriceoff: "$$195.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 5 Retro",
    img: "../pic/subjorden3-3.avif",
    categoies: "Khmer New Year Sale502",
    usPrice: "$140.00",
    usPriceoff: "$$195.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 503,
    subId: 501,
    name: "Air Jordan 5 Retro",
    price: "223$",
    img: "../pic/jorden4.avif",
    categoies: "Khmer New Year Sale503",
    usPrice: "$200.99",
    usPriceoff: "$240.95",
    Priceoff: "-40%",
    typeOfShirt: "jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 5 Retro",
    img: "../pic/subjorden4-1.avif",
    categoies: "Khmer New Year Sale503",
    usPrice: "$200.00",
    usPriceoff: "$255.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 5 Retro",
    img: "../pic/subjorden4-2.avif",
    categoies: "Khmer New Year Sale503",
    usPrice: "$200.00",
    usPriceoff: "$255.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 5 Retro",
    img: "../pic/subjorden4-3.avif",
    categoies: "Khmer New Year Sale503",
    usPrice: "$200.00",
    usPriceoff: "$255.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 5 Retro",
    img: "../pic/subjorden4-4.avif",
    categoies: "Khmer New Year Sale503",
    usPrice: "$200.00",
    usPriceoff: "$255.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  // bag
  {
    id: 504,
    subId: 505,
    name: "Nike Utility Power",
    price: "100$",
    img: "../pic/bag1.avif",
    categoies: "Khmer New Year Sale504",
    usPrice: "$100.99",
    usPriceoff: "$140.95",
    Priceoff: "-40%",
    typeOfShirt: "bag",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 5 Retro",
    img: "../pic/subbag1.avif",
    categoies: "Khmer New Year Sale504",
    usPrice: "$200.00",
    usPriceoff: "$255.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 5 Retro",
    img: "../pic/subbag2.avif",
    categoies: "Khmer New Year Sale504",
    usPrice: "$200.00",
    usPriceoff: "$255.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 5 Retro",
    img: "../pic/subbag3.avif",
    categoies: "Khmer New Year Sale504",
    usPrice: "$200.00",
    usPriceoff: "$255.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 5 Retro",
    img: "../pic/subbag4.avif",
    categoies: "Khmer New Year Sale504",
    usPrice: "$200.00",
    usPriceoff: "$255.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 505,
    subId: 504,
    name: "Nike Utility Power",
    price: "100$",
    img: "../pic/bag2.avif",
    categoies: "Khmer New Year Sale505",
    usPrice: "$100.99",
    usPriceoff: "$140.95",
    Priceoff: "-40%",
    typeOfShirt: "bag",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 5 Retro",
    img: "../pic/subbag2-1.avif",
    categoies: "Khmer New Year Sale505",
    usPrice: "$57.00",
    usPriceoff: "$105.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 5 Retro",
    img: "../pic/subbag2-2.avif",
    categoies: "Khmer New Year Sale505",
    usPrice: "$57.00",
    usPriceoff: "$100.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 5 Retro",
    img: "../pic/subbag2-3.avif",
    categoies: "Khmer New Year Sale505",
    usPrice: "$57.00",
    usPriceoff: "$105.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 5 Retro",
    img: "../pic/subbag2-4.avif",
    categoies: "Khmer New Year Sale505",
    usPrice: "$57.00",
    usPriceoff: "$100.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 506,
    subId: 507,
    name: "Nike Utility Power",
    price: "100$",
    img: "../pic/bag3.avif",
    categoies: "Khmer New Year Sale506",
    usPrice: "$100.99",
    usPriceoff: "$140.95",
    Priceoff: "-40%",
    typeOfShirt: "bag",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 5 Retro",
    img: "../pic/subbag3-1.avif",
    categoies: "Khmer New Year Sale506",
    usPrice: "$57.00",
    usPriceoff: "$100.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 5 Retro",
    img: "../pic/subbag3-2.avif",
    categoies: "Khmer New Year Sale506",
    usPrice: "$57.00",
    usPriceoff: "$100.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 5 Retro",
    img: "../pic/subbag3-3.avif",
    categoies: "Khmer New Year Sale506",
    usPrice: "$57.00",
    usPriceoff: "$100.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 5 Retro",
    img: "../pic/subbag3-4.avif",
    categoies: "Khmer New Year Sale506",
    usPrice: "$57.00",
    usPriceoff: "$100.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 507,
    subId: 506,
    name: "Nike Utility Power",
    price: "100$",
    img: "../pic/bag4.avif",
    categoies: "Khmer New Year Sale507",
    usPrice: "$100.99",
    usPriceoff: "$140.95",
    Priceoff: "-40%",
    typeOfShirt: "bag",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 5 Retro",
    img: "../pic/subbag4-1.avif",
    categoies: "Khmer New Year Sale507",
    usPrice: "$57.00",
    usPriceoff: "$100.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 5 Retro",
    img: "../pic/subbag4-2.avif",
    categoies: "Khmer New Year Sale507",
    usPrice: "$57.00",
    usPriceoff: "$100.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 5 Retro",
    img: "../pic/subbag4-3.avif",
    categoies: "Khmer New Year Sale507",
    usPrice: "$57.00",
    usPriceoff: "$100.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 5 Retro",
    img: "../pic/subbag4-1.avif",
    categoies: "Khmer New Year Sale507",
    usPrice: "$57.00",
    usPriceoff: "$100.00",
    Priceoff: "-40%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 508,
    subId: 500,
    name: "Nike Utility Power",
    price: "100$",
    img: "../pic/jordanP5.avif",
    categoies: "Khmer New Year Sale508",
    usPrice: "$100.99",
    usPriceoff: "$140.95",
    Priceoff: "-40%",
    typeOfShirt: "bag",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Nike C1TY",
    img: "../pic/jorden5.avif",
    categoies: "Khmer New Year Sale508",
    usPrice: "$100.00",
    usPriceoff: "$130.00",
    Priceoff: "-20%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Nike C1TY",
    img: "../pic/subjorden5-1.avif",
    categoies: "Khmer New Year Sale508",
    usPrice: "$100.00",
    usPriceoff: "$130.00",
    Priceoff: "-20%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Nike C1TY",
    img: "../pic/subjorden5-2.avif",
    categoies: "Khmer New Year Sale508",
    usPrice: "$100.00",
    usPriceoff: "$130.00",
    Priceoff: "-20%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Nike C1TY",
    img: "../pic/subjorden5-3.avif",
    categoies: "Khmer New Year Sale508",
    usPrice: "$100.00",
    usPriceoff: "$130.00",
    Priceoff: "-20%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Nike C1TY",
    img: "../pic/subjorden5-4.avif",
    categoies: "Khmer New Year Sale508",
    usPrice: "$100.00",
    usPriceoff: "$130.00",
    Priceoff: "-20%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 509,
    subId: 500,
    name: "Nike JordenSpike",
    price: "100$",
    img: "../pic/jorden6.avif",
    categoies: "Khmer New Year Sale509",
    usPrice: "$160.99",
    usPriceoff: "$140.95",
    Priceoff: "-10%",
    typeOfShirt: "jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Nike JordenSpike",
    img: "../pic/subjorden6-1.avif",
    categoies: "Khmer New Year Sale509",
    usPrice: "$160.00",
    usPriceoff: "$120.00",
    Priceoff: "-10%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Nike JordenSpike",
    img: "../pic/subjorden6-2.avif",
    categoies: "Khmer New Year Sale509",
    usPrice: "$160.00",
    usPriceoff: "$120.00",
    Priceoff: "-10%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Nike JordenSpike",
    img: "../pic/subjorden6-3.avif",
    categoies: "Khmer New Year Sale509",
    usPrice: "$160.00",
    usPriceoff: "$120.00",
    Priceoff: "-10%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Nike JordenSpike",
    img: "../pic/subjorden6-4.avif",
    categoies: "Khmer New Year Sale509",
    usPrice: "$160.00",
    usPriceoff: "$120.00",
    Priceoff: "-10%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 510,
    subId: 500,
    name: "Nike Tatum 3",
    price: "125$",
    img: "../pic/jorden7.avif",
    categoies: "Khmer New Year Sale510",
    usPrice: "$125.99",
    usPriceoff: "$140.95",
    Priceoff: "-10%",
    typeOfShirt: "jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Nike JordenSpike",
    img: "../pic/subjorden7-1.avif",
    categoies: "Khmer New Year Sale510",
    usPrice: "$160.00",
    usPriceoff: "$120.00",
    Priceoff: "-10%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Nike JordenSpike",
    img: "../pic/subjorden7-2.avif",
    categoies: "Khmer New Year Sale510",
    usPrice: "$160.00",
    usPriceoff: "$120.00",
    Priceoff: "-10%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Nike JordenSpike",
    img: "../pic/subjorden7-3.avif",
    categoies: "Khmer New Year Sale510",
    usPrice: "$160.00",
    usPriceoff: "$120.00",
    Priceoff: "-10%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Nike JordenSpike",
    img: "../pic/subjorden7-4.avif",
    categoies: "Khmer New Year Sale510",
    usPrice: "$160.00",
    usPriceoff: "$120.00",
    Priceoff: "-10%",
    typeOfShirt: "Jordan",
    MaxQuantity: 50,
    similar: "top",
  },

  // basketball
  {
    id: 511,
    name: "Nike G.T. Hustle 3",
    price: "190$",
    img: "../pic/bas1.avif",
    categoies: "Khmer New Year Sale511",
    usPrice: "$190.99",
    usPriceoff: "$200.95",
    Priceoff: "-10%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Nike JordenSpike",
    img: "../pic/subbas1.avif",
    categoies: "Khmer New Year Sale511",
    usPrice: "$190.99",
    usPriceoff: "$200.95",
    Priceoff: "-10%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Nike JordenSpike",
    img: "../pic/subbas2.avif",
    categoies: "Khmer New Year Sale511",
    usPrice: "$190.99",
    usPriceoff: "$200.95",
    Priceoff: "-10%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Nike JordenSpike",
    img: "../pic/subbas3.avif",
    categoies: "Khmer New Year Sale511",
    usPrice: "$190.99",
    usPriceoff: "$200.95",
    Priceoff: "-10%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Nike JordenSpike",
    img: "../pic/subbas4.avif",
    categoies: "Khmer New Year Sale511",
    usPrice: "$190.99",
    usPriceoff: "$200.95",
    Priceoff: "-10%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 512,
    subId: 511,
    name: "Nike KD18",
    price: "190$",
    img: "../pic/bas2.avif",
    categoies: "Khmer New Year Sale512",
    usPrice: "$160.99",
    usPriceoff: "$200.95",
    Priceoff: "-20%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Nike KD18",
    img: "../pic/subbas2-1.avif",
    categoies: "Khmer New Year Sale512",
    usPrice: "$160.99",
    usPriceoff: "$200.95",
    Priceoff: "-20%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Nike KD18",
    img: "../pic/subbas2-2.avif",
    categoies: "Khmer New Year Sale512",
    usPrice: "$160.99",
    usPriceoff: "$200.95",
    Priceoff: "-20%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Nike KD18",
    img: "../pic/subbas2-3.avif",
    categoies: "Khmer New Year Sale512",
    usPrice: "$160.99",
    usPriceoff: "$200.95",
    Priceoff: "-20%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Nike KD18",
    img: "../pic/subbas2-4.avif",
    categoies: "Khmer New Year Sale512",
    usPrice: "$160.99",
    usPriceoff: "$200.95",
    Priceoff: "-20%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 513,
    subId: 511,
    name: "Sabrina 2",
    price: "130$",
    img: "../pic/bas3.avif",
    categoies: "Khmer New Year Sale513",
    usPrice: "$130.99",
    usPriceoff: "$160.95",
    Priceoff: "-20%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Sabrina 2",
    img: "../pic/subbas3-1.avif",
    categoies: "Khmer New Year Sale513",
    usPrice: "$130.99",
    usPriceoff: "$160.95",
    Priceoff: "-20%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Sabrina 2",
    img: "../pic/subbas3-2.avif",
    categoies: "Khmer New Year Sale513",
    usPrice: "$130.99",
    usPriceoff: "$160.95",
    Priceoff: "-20%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Sabrina 2",
    img: "../pic/subbas3-3.avif",
    categoies: "Khmer New Year Sale513",
    usPrice: "$130.99",
    usPriceoff: "$160.95",
    Priceoff: "-20%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Sabrina 2",
    img: "../pic/subbas3-4.avif",
    categoies: "Khmer New Year Sale513",
    usPrice: "$130.99",
    usPriceoff: "$160.95",
    Priceoff: "-20%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 514,
    subId: 511,
    name: "Giannis Immortality 4",
    price: "130$",
    img: "../pic/bas4.avif",
    categoies: "Khmer New Year Sale514",
    usPrice: "$85.99",
    usPriceoff: "$100.95",
    Priceoff: "-20%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Giannis Immortality 4",
    img: "../pic/subbas4-1.avif",
    categoies: "Khmer New Year Sale514",
    usPrice: "$130.99",
    usPriceoff: "$160.95",
    Priceoff: "-20%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Giannis Immortality 4",
    img: "../pic/subbas4-2.avif",
    categoies: "Khmer New Year Sale514",
    usPrice: "$130.99",
    usPriceoff: "$160.95",
    Priceoff: "-20%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Giannis Immortality 4",
    img: "../pic/subbas4-3.avif",
    categoies: "Khmer New Year Sale514",
    usPrice: "$130.99",
    usPriceoff: "$160.95",
    Priceoff: "-20%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Giannis Immortality 4",
    img: "../pic/subbas4-4.avif",
    categoies: "Khmer New Year Sale514",
    usPrice: "$130.99",
    usPriceoff: "$160.95",
    Priceoff: "-20%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 515,
    subId: 511,
    name: "LeBron XXII",
    price: "190$",
    img: "../pic/bas5.avif",
    categoies: "Khmer New Year Sale515",
    usPrice: "$190.99",
    usPriceoff: "$200.95",
    Priceoff: "-10%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Giannis Immortality 4",
    img: "../pic/subbas5-1.avif",
    categoies: "Khmer New Year Sale515",
    usPrice: "$190.99",
    usPriceoff: "$200.95",
    Priceoff: "-10%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Giannis Immortality 4",
    img: "../pic/subbas5-2.avif",
    categoies: "Khmer New Year Sale515",
    usPrice: "$190.99",
    usPriceoff: "$200.95",
    Priceoff: "-10%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Giannis Immortality 4",
    img: "../pic/subbas5-3.avif",
    categoies: "Khmer New Year Sale515",
    usPrice: "$190.99",
    usPriceoff: "$200.95",
    Priceoff: "-10%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Giannis Immortality 4",
    img: "../pic/subbas5-4.avif",
    categoies: "Khmer New Year Sale515",
    usPrice: "$190.99",
    usPriceoff: "$200.95",
    Priceoff: "-10%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 516,
    subId: 511,
    name: "LeBron NXXT ",
    price: "160$",
    img: "../pic/bas6.avif",
    categoies: "Khmer New Year Sale516",
    usPrice: "$160.99",
    usPriceoff: "$200.95",
    Priceoff: "-30%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "LeBron NXXT ",
    img: "../pic/subbas6-1.avif",
    categoies: "Khmer New Year Sale516",
    usPrice: "$160.99",
    usPriceoff: "$200.95",
    Priceoff: "-30%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "LeBron NXXT ",
    img: "../pic/subbas6-2.avif",
    categoies: "Khmer New Year Sale516",
    usPrice: "$160.99",
    usPriceoff: "$200.95",
    Priceoff: "-30%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "LeBron NXXT ",
    img: "../pic/subbas6-3.avif",
    categoies: "Khmer New Year Sale516",
    usPrice: "$160.99",
    usPriceoff: "$200.95",
    Priceoff: "-30%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "LeBron NXXT ",
    img: "../pic/subbas6-4.avif",
    categoies: "Khmer New Year Sale516",
    usPrice: "$160.99",
    usPriceoff: "$200.95",
    Priceoff: "-30%",
    typeOfShirt: "basketball",
    MaxQuantity: 50,
    similar: "top",
  },
  // life style
  {
    id: 517,
    subId: 502,
    name: "Air Jordan 11 Retro Low",
    price: "160$",
    img: "../pic/l1.avif",
    categoies: "Khmer New Year Sale517",
    usPrice: "$190.99",
    usPriceoff: "$200.95",
    Priceoff: "-10%",
    typeOfShirt: "lifestyle",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 11 Retro Low",
    img: "../pic/subl1.avif",
    categoies: "Khmer New Year Sale517",
    usPrice: "$160.99",
    usPriceoff: "$200.95",
    Priceoff: "-30%",
    typeOfShirt: "lifestyle",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 11 Retro Low",
    img: "../pic/subl2.avif",
    categoies: "Khmer New Year Sale517",
    usPrice: "$160.99",
    usPriceoff: "$200.95",
    Priceoff: "-30%",
    typeOfShirt: "lifestyle",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 11 Retro Low",
    img: "../pic/subl3.avif",
    categoies: "Khmer New Year Sale517",
    usPrice: "$160.99",
    usPriceoff: "$200.95",
    Priceoff: "-30%",
    typeOfShirt: "lifestyle",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Air Jordan 11 Retro Low",
    img: "../pic/subl4.avif",
    categoies: "Khmer New Year Sale517",
    usPrice: "$160.99",
    usPriceoff: "$200.95",
    Priceoff: "-30%",
    typeOfShirt: "lifestyle",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 518,
    subId: 502,
    name: "Nike Air Max 95 OG",
    price: "180$",
    img: "../pic/l2.avif",
    categoies: "Khmer New Year Sale518",
    usPrice: "$180.99",
    usPriceoff: "$200.95",
    Priceoff: "-20%",
    typeOfShirt: "lifestyle",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "Nike Air Max 95 OG",
    img: "../pic/subl2-1.avif",
    categoies: "Khmer New Year Sale518",
    usPrice: "$180.99",
    usPriceoff: "$200.95",
    Priceoff: "-20%",
    typeOfShirt: "lifestyle",
    MaxQuantity: 50,
    similar: "top",
  },
  // Women
  {
    id: 200,
    subId: 40,
    name: "img1",
    img: "../pic/womenshort1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale29",
    usPrice: "$40.99",
    usPriceoff: "$60.95",
    Priceoff: "-40%",
    typeOfShirt: "Pants And Tights",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/subleg1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale29",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Legging",
    MaxQuantity: 50,
    similar: "top",
  },
  //kid
  {
    id: 300,
    subId: 301,
    subId: 302,
    name: "img1",
    img: "../pic/subkid1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale300",
    usPrice: "$10.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Men",
  },
  {
    name: "img1",
    img: "../pic/subkid2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale300",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Men",
  },
  {
    name: "img1",
    img: "../pic/subkid3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale300",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Men",
  },
  {
    name: "img1",
    img: "../pic/subkid4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale300",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Men",
  },
  {
    id: 301,
    subId: 300,
    subId: 302,
    name: "img1",
    img: "../pic/subkidsport1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale301",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Kid",
  },
  {
    name: "img1",
    img: "../pic/subkidsport2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale301",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Kid",
  },
  {
    name: "img1",
    img: "../pic/subkidsport3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale301",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Kid",
  },
  {
    name: "img1",
    img: "../pic/subkidsport4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale301",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Kid",
  },
  {
    id: 302,
    subId: 301,
    subId: 300,
    name: "img1",
    img: "../pic/subkidwhite1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale302",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Men",
  },
  {
    name: "img1",
    img: "../pic/subkidwhite2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale302",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Men",
  },
  {
    name: "img1",
    img: "../pic/subkidwhite3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale302",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Men",
  },
  {
    name: "img1",
    img: "../pic/subkidwhite4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale302",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Men",
  },
  {
    id: 303,
    subId: 300,
    subId: 302,
    subId: 301,
    name: "img1",
    img: "../pic/subkidblack1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale303",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Men",
  },
  {
    name: "img1",
    img: "../pic/subkidblack2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale303",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Men",
  },
  {
    name: "img1",
    img: "../pic/subkidblack3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale303",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Men",
  },
  {
    name: "img1",
    img: "../pic/subkidblack4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale303",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Men",
  },
  {
    id: 304,
    subId: 300,
    name: "img1",
    img: "../pic/subkidblue1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale304",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Men",
  },
  {
    name: "img1",
    img: "../pic/subkidblue2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale304",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Men",
  },
  {
    name: "img1",
    img: "../pic/subkidblue3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale304",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Men",
  },
  {
    name: "img1",
    img: "../pic/subkidblue4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale304",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Men",
  },
  {
    id: 305,
    subId: 301,
    name: "img1",
    img: "../pic/subkidgray1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale305",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Men",
  },
  {
    subId: 300,
    name: "img1",
    img: "../pic/subkidgray1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale305",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Men",
  },
  {
    subId: 302,
    name: "img1",
    img: "../pic/subkidgray1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale305",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Men",
  },
  {
    subId: 303,
    name: "img1",
    img: "../pic/subkidgray1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale305",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Men",
  },
  {
    subId: 304,
    name: "img1",
    img: "../pic/subkidgray1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale305",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Men",
  },
  {
    id: 306,
    subId: 301,
    name: "img1",
    img: "../pic/subkidyellow1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale306",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Men",
  },
  {
    subId: 300,
    name: "img1",
    img: "../pic/subkidyellow1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale306",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Men",
  },
  {
    name: "img1",
    img: "../pic/subkidyellow2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale306",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Men",
  },
  {
    name: "img1",
    img: "../pic/subkidyellow3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale306",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Men",
  },
  {
    name: "img1",
    img: "../pic/subkidyellow4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale306",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Men",
  },

  {
    subId: 302,
    name: "img1",
    img: "../pic/subkidyellow1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale306",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Men",
  },
  {
    id: 400,
    subId: 401,
    name: "img1",
    img: "../pic/ac1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale400",
    usPrice: "$69.99",
    // usPriceoff: "$60.95",
    // Priceoff: "-40%",
    typeOfShirt: "Nike Aura",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/ac2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale400",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Legging",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/Nike Aura3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale400",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Legging",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/Nike Aura4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale400",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Legging",
    MaxQuantity: 50,
    similar: "top",
  },
  // Ac Bag Nike Utility
  {
    id: 401,
    subId: 400,
    name: "img1",
    img: "../pic/Nike Utility Speed 1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale401",
    usPrice: "$84.99",
    usPriceoff: "$99.99",
    // Priceoff: "-40%",
    typeOfShirt: "Nike Utility Speed",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/Nike Utility Speed 2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale401",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Legging",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/Nike Utility Speed 3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale401",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Legging",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/Nike Utility Speed 4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale401",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Legging",
    MaxQuantity: 50,
    similar: "top",
  },
  // Jordan alpha
  {
    id: 402,
    subId: 400,
    name: "img1",
    img: "../pic/Jordan Alpha 1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale402",
    usPrice: "$54.99",
    usPriceoff: "$35.97",
    Priceoff: "-34%",
    typeOfShirt: "Jordan Alpha Mini Backpack (9L)",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    name: "img1",
    img: "../pic/Jordan Alpha 2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale402",
  },
  {
    name: "img1",
    img: "../pic/Jordan Alpha 3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale402",
  },
  {
    name: "img1",
    img: "../pic/Jordan Alpha 4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale402",
  },
  // Nike Sportswear Essentials
  {
    id: 403,
    subId: 400,
    name: "img1",
    img: "../pic/Jordan Alpha 1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale402",
    usPrice: "$54.99",
    usPriceoff: "$35.97",
    Priceoff: "-34%",
    typeOfShirt: "Jordan Alpha Mini Backpack (9L)",
    MaxQuantity: 50,
    similar: "top",
  },
];

let imageList = [];
let currentIndex = 0;
let currentImages = [];
const params = new URLSearchParams(window.location.search);
const id = parseInt(params.get("id"));
const product = dataSmall.find((p) => p.id === id);
// Update the main image
function updateMainImage(index) {
  const mainImage = document.getElementById("mainImage");
  const thumbnails = document.querySelectorAll(".thumbnails img");

  thumbnails.forEach((img) => img.classList.remove("active"));
  if (thumbnails[index]) thumbnails[index].classList.add("active");
  // Slide out current image
  mainImage.classList.remove("show");
  mainImage.classList.add("slide-out-left");

  setTimeout(() => {
    mainImage.src = currentImages[index];

    // Slide in new image
    mainImage.onload = () => {
      mainImage.classList.remove("slide-out-left");
      mainImage.classList.add("slide-in-right");

      setTimeout(() => {
        mainImage.classList.remove("slide-in-right");
        mainImage.classList.add("show");
      }, 50); // Small delay to trigger the transition
    };
  }, 300);
}
function selectImage(index) {
  currentIndex = index;
  updateMainImage(index);
}
function nextImage() {
  currentIndex = (currentIndex + 1) % currentImages.length;
  updateMainImage(currentIndex);
}
function prevImage() {
  currentIndex =
    (currentIndex - 1 + currentImages.length) % currentImages.length;
  updateMainImage(currentIndex);
}
window.addEventListener("DOMContentLoaded", () => {
  const thumbnailContainer = document.getElementById("thumbnailContainer");
  const mainImage = document.getElementById("mainImage");
  if (!product) {
    document.body.innerHTML =
      '<a href="../index.html" classs"m-auto"><img src="../pic/4044.gif" alt="" class="w-100" style="height: 600px;margin"></a> ';
    return;
  }
  // Use "categoies" since it's what's used in your data — but fix in real data!
  const category = product.categoies;
  if (!category) {
    document.body.innerHTML =
      '    <a href="../index.html"><img src="../pic/nott.gif" alt="" class="w-100 h-auto"></a>';
    return;
  }
  // Get all images from products in the same category
  const sameCategoryItems = dataSmall.filter(
    (item) => item.categoies === category
  );
  imageList = sameCategoryItems.map((item) => item.img);
  // Remove duplicates
  imageList = [...new Set(imageList)];
  currentImages = imageList;
  currentIndex = currentImages.indexOf(product.img);
  if (currentIndex === -1) currentIndex = 0;

  mainImage.src = currentImages[currentIndex];

  // Create thumbnails
  thumbnailContainer.innerHTML = "";
  currentImages.forEach((imgSrc, index) => {
    const img = document.createElement("img");
    img.src = imgSrc;
    img.alt = `Thumbnail ${index + 1}`;
    img.classList.add("thumbnail");
    if (index === currentIndex) img.classList.add("active");

    img.addEventListener("click", () => selectImage(index));
    thumbnailContainer.appendChild(img);
  });
});

// size

const sizexs = document.querySelector(".size-Xs");
const sizes = document.querySelector(".size-S");
const sizeM = document.querySelector(".size-M");
const sizeL = document.querySelector(".size-L");

sizexs.addEventListener("click", () => {
  sizexs.classList.toggle("sizeSelected");
  sizexs.innerHTML = "XS";
  sizes.classList.remove("sizeSelected");
  sizeM.classList.remove("sizeSelected");
  sizeL.classList.remove("sizeSelected");
});
sizes.addEventListener("click", () => {
  sizes.classList.toggle("sizeSelected");
  sizes.innerHTML = "S";
  sizexs.classList.remove("sizeSelected");
  sizeM.classList.remove("sizeSelected");
  sizeL.classList.remove("sizeSelected");
});
sizeM.addEventListener("click", () => {
  sizeM.innerHTML = "M";
  sizeM.classList.toggle("sizeSelected");
  sizexs.classList.remove("sizeSelected");
  sizes.classList.remove("sizeSelected");
  sizeL.classList.remove("sizeSelected");
});
sizeL.addEventListener("click", () => {
  sizeL.classList.toggle("sizeSelected");
  sizeL.innerHTML = "L";
  sizexs.classList.remove("sizeSelected");
  sizes.classList.remove("sizeSelected");
  sizeM.classList.remove("sizeSelected");
  console.log(sizeL.textContent);
});

const increment = document.querySelector(".increment");
const decrement = document.querySelector(".decrement");
const resultQTY = document.querySelector(".resultQTY");
const btnSub = document.querySelector(".btn-sub");
const result = document.querySelector(".result");
const wrapperitems = document.querySelector(".wrapper-items");
const sizeitem = document.querySelector(".sizeitem");
const qtryitem = document.querySelector(".qtyitem");

resultQTY.innerHTML = 0;
result.innerHTML = 0;
sizeitem.innerHTML = "";
increment.addEventListener("click", function () {
  if (resultQTY.innerHTML >= product.MaxQuantity) {
    alert("Please input Low qty");
    return;
  }
  resultQTY.innerHTML = parseInt(resultQTY.innerHTML) + 1;
});
decrement.addEventListener("click", function () {
  if (resultQTY.innerHTML <= 0) {
    resultQTY.innerHTML = 0;
  } else {
    resultQTY.innerHTML = parseInt(resultQTY.innerHTML) - 1;
  }
});
const udprice = document.querySelector(".usPrice");
const offPrice = document.querySelector(".offPrice");
const usPriceoff = document.querySelector(".usPriceoff");
const typeOfShirt = document.querySelector(".typeOfShirt");
const udpricevart = document.querySelector(".usPricecart");
const offPricecart = document.querySelector(".offPricecart");
const usPriceoffcart = document.querySelector(".usPriceoffcart");
const typeOfShirtcart = document.querySelector(".typeOfShirtcart");
const totalPrice = document.querySelector(".totalPrice");
if (udprice || offPrice || usPriceoff) {
  usPriceoff.textContent = product.usPriceoff;
  udprice.textContent = product.usPrice;
  offPrice.textContent = product.Priceoff;
  typeOfShirt.textContent = product.typeOfShirt;
}
// Bag
let totalQuantity = 0; // Keep track of all items added
btnSub.addEventListener("click", function () {
  const quantity = parseInt(resultQTY.innerHTML);
  const selectedSize = document.querySelector(".sizeSelected");
  if (!selectedSize) {
    alert("Please select a size before adding to cart.");
    return;
  }
  if (quantity <= 0) {
    alert("Please choose a quantity greater than 0.");
    return;
  }

  // ✅ Update total result
  totalQuantity += quantity;
  result.innerHTML = totalQuantity;

  // ✅ Get selected image
  const selectedImageSrc = document.getElementById("mainImage").src;

  // ✅ Add to cart
  const cartItem = {
    id: product.id,
    name: product.name,
    size: selectedSize.textContent,
    quantity: quantity,
    image: selectedImageSrc,
    usPriceoff: product.usPriceoff,
    udprice: product.price,
    offPrice: product.Priceoff,
    typeOfShirt: product.typeOfShirt,
    MaxQty: product.MaxQuantity,
  };
  let cart = JSON.parse(localStorage.getItem("cart")) || [];

  // ✅ Check if same size already in cart — if so, update quantity
  const existingItem = cart.find(
    (item) => item.id === product.id && item.size === cartItem.size
  );

  if (existingItem) {
    existingItem.quantity += quantity;
  } else {
    cart.push(cartItem);
  }
  localStorage.setItem("cart", JSON.stringify(cart));

  // ✅ Add UI preview
  const sizeDiv = document.createElement("div");
  sizeDiv.classList.add("ordered-size");
  sizeDiv.setAttribute("data-size", selectedSize.textContent);
  sizeDiv.innerHTML = `Your Ordered: [${selectedSize.textContent}: ${quantity}] 
    <button class="removeSizeBtn btn-size mt-2" data-size="${selectedSize.textContent}"><i class="bi bi-trash3-fill"></i></button>`;
  sizeitem.appendChild(sizeDiv);
  // ✅ Add remove handler
  sizeDiv
    .querySelector(".removeSizeBtn")
    .addEventListener("click", function () {
      const sizeToRemove = this.getAttribute("data-size");
      let cart = JSON.parse(localStorage.getItem("cart")) || [];
      cart = cart.filter((item) => item.size !== sizeToRemove);
      localStorage.setItem("cart", JSON.stringify(cart));

      sizeDiv.remove();

      // Recalculate totals
      totalQuantity = 0;
      let totalCost = 0;
      cart.forEach((item) => {
        totalQuantity += item.quantity;
        const price = parseFloat(item.usPriceoff.replace("$", ""));
        totalCost += price * item.quantity;
      });

      result.innerHTML = totalQuantity;
      qtryitem.innerHTML = "Quantity: " + totalQuantity;
      totalPrice.innerHTML = "Total US $" + totalCost.toFixed(2);
      alert(`Removed size ${sizeToRemove} from cart.`);
      const previewImg1 = document.querySelector(".cart-preview-img");
      if (previewImg1 && totalQuantity == 0) {
        previewImg1.src = "";
      }
    });

  // ✅ Update quantity and price
  qtryitem.innerHTML = "Quantity: " + totalQuantity;

  const cleanPrice = parseFloat(product.usPrice.replace("$", ""));
  const itemTotalPrice = cleanPrice * totalQuantity;
  totalPrice.textContent = "Total US $" + itemTotalPrice.toFixed(2);

  // ✅ Show preview
  let previewImg = document.querySelector(".cart-preview-img");
  if (!previewImg) {
    previewImg = document.createElement("img");
    previewImg.classList.add("cart-preview-img");
    document.body.appendChild(previewImg);
  }
  previewImg.src = selectedImageSrc;

  // ✅ Display product details
  if (udpricevart || offPricecart || usPriceoffcart) {
    udpricevart.textContent = product.usPrice;
    offPricecart.textContent = product.Priceoff;
    usPriceoffcart.textContent = product.usPriceoff;
    typeOfShirtcart.textContent = product.typeOfShirt;
  }

  // ✅ Reset input
  resultQTY.innerHTML = 0;
  selectedSize.classList.remove("sizeSelected");

  // ✅ Activate clear button
  const btnclear = document.querySelector(".btn-clear");
  // btnclear.innerHTML = "ClearForm";
  btnclear.classList.add("active");

  btnclear.addEventListener("click", function () {
    localStorage.removeItem("cart");
    totalQuantity = 0;
    result.innerHTML = 0;
    qtryitem.innerHTML = 0;
    sizeitem.innerHTML = "";
    usPriceoffcart.innerHTML = "";
    offPricecart.innerHTML = "";
    udpricevart.innerHTML = "";
    totalPrice.innerHTML = "";
    typeOfShirtcart.textContent = "No Information";

    const previewImg = document.querySelector(".cart-preview-img");
    if (previewImg) {
      previewImg.src = "";
    }
    // Reset size buttons
    document.querySelector(".size-Xs")?.classList.remove("sizeSelected");
    document.querySelector(".size-S")?.classList.remove("sizeSelected");
    document.querySelector(".size-M")?.classList.remove("sizeSelected");
    document.querySelector(".size-L")?.classList.remove("sizeSelected");
    document.querySelector(".size-Xs").textContent = "XS";
    document.querySelector(".size-S").textContent = "S";
    document.querySelector(".size-M").textContent = "M";
    document.querySelector(".size-L").textContent = "L";
    // Clear localStorage for orders
    const orders = JSON.parse(localStorage.getItem("orders")) || [];
    const updatedOrders = orders.filter((order) => order.id !== product.id);
    localStorage.setItem("orders", JSON.stringify(updatedOrders));
    // If on dashboard.html, reload the page to reflect changes
    if (window.location.pathname.includes("dashboard.html")) {
      location.reload();
    }
    alert("Cart has been cleared.");
    btnclear.classList.remove("active");
  });

  alert(
    `Added to cart: ${cartItem.name} [Size: ${cartItem.size}, Qty: ${cartItem.quantity}]\n` +
      `Price per item: ${product.usPrice}\n` +
      `Total for this item: $${itemTotalPrice.toFixed(2)}`
  );
  console.log(quantity);
  console.log(totalQuantity);
  const orders = JSON.parse(localStorage.getItem("orders")) || [];
  const orderItem = {
    ...cartItem,
    date: Date.now(),
  };
  orders.push(orderItem);
  localStorage.setItem("orders", JSON.stringify(orders));
});
// similar
const wrappersimilar = document.querySelector(".wrapper-similar");
console.log(product.id);
console.log(id);
if (product.id == id) {
  wrappersimilar.innerHTML = dataSmall
    .filter((e) => {
      return e.subId == id;
    })
    .map((a) => {
      return ` 
            <div class="col-lg-3 mb-4 col-6">
                <div class="image-card-wrapper w-100 overflow-hidden">
                    <a href="data.html?id=${a.id}">
                        <img src="${a.img}" class="${a.class}" alt="${a.name}">
                    </a>
                </div>
                <div class="wrapper-similar-text mt-3 overflow-hidden">
                    <div class="wrapper-hover">
                    <div class="wrapper-flex-text d-flex justify-content-between align-items-center ">
                        <h5 class="fw-bold text-dark m-0 price-text">US ${a.usPrice}</h5>
        <h5 class=" text-dark fw-bolder clickFav" id="offcanvasRightLabel"><i class="fa-regular fa-heart clickHeart"></i>
        </h5>
    </div>
    <span class="offPriceShow">${a.usPriceoff}</span>
                                    <div class="flex-img d-flex justify-content-between align-items-center"> 
                                    <p class="fw-light pt-1 mb-0">${a.typeOfShirt}</p>
                                    <a href="data.html?id=${a.id}">
                        <img src="${a.img}" class="${a.class} img-price" alt="${a.name}" style="width:35px;height: 35px;">
                    </a>
                </div>
                </div>
                </div>
            </div>
          `;
    })
    .join("");

  console.log(wrappersimilar);
}
// Add after your existing code

function addToFavorites() {
  const mainImage = document.getElementById("mainImage");
  const selectedSize = document.querySelector(".sizeSelected");

  if (!selectedSize) {
    alert("Please select a size first");
    return;
  }

  const favoriteItem = {
    id: product.id,
    name: product.name,
    img: mainImage.src,
    typeOfShirt: product.typeOfShirt,
    price: product.usPrice,
    priceOff: product.Priceoff,
    usPriceoff: product.usPriceoff,
    size: selectedSize.textContent,
  };

  // Get existing favorites
  let favorites = JSON.parse(localStorage.getItem("favorites")) || [];

  // Check if item already exists
  const existingIndex = favorites.findIndex(
    (item) => item.id === favoriteItem.id && item.size === favoriteItem.size
  );

  if (existingIndex !== -1) {
    // Item exists, remove it
    favorites.splice(existingIndex, 1);
    showToast("Removed from favorites");
    document.querySelector(".btnFav i").classList.remove("fa-solid");
    document.querySelector(".btnFav i").classList.add("fa-regular");
  } else {
    // Add new item
    favorites.push(favoriteItem);
    showToast("Added to favorites");
    document.querySelector(".btnFav i").classList.remove("fa-regular");
    document.querySelector(".btnFav i").classList.add("fa-solid");
  }

  localStorage.setItem("favorites", JSON.stringify(favorites));
}

function showToast(message) {
  const toast = document.createElement("div");
  toast.className = "toast-notification";
  toast.textContent = message;
  document.body.appendChild(toast);

  setTimeout(() => {
    toast.remove();
  }, 2000);
  window.location.href = "./AddFav.html";
}

// Check if item is in favorites on page load
document.addEventListener("DOMContentLoaded", function () {
  const favorites = JSON.parse(localStorage.getItem("favorites")) || [];
  const isInFavorites = favorites.some((item) => item.id === product.id);

  if (isInFavorites) {
    document.querySelector(".btnFav i").classList.remove("fa-regular");
    document.querySelector(".btnFav i").classList.add("fa-solid");
  }
});
// dropdown info
const headers = document.querySelectorAll(".dropdown-header");
headers.forEach((header) => {
  header.addEventListener("click", () => {
    const content = header.querySelector(".wrapper-infoText"); // Get the next .dropdown-content
    const chevron = header.querySelector(".chevron");

    // Toggle active class for content
    content.classList.toggle("active");

    // Toggle icon class
    if (content.classList.contains("active")) {
      chevron.classList.remove("fa-chevron-down");
      chevron.classList.add("fa-chevron-up");
    } else {
      chevron.classList.remove("fa-chevron-up");
      chevron.classList.add("fa-chevron-down");
    }
  });
});
