const dataSmall = [
  {
    id: 1,
    subId: 5,
    name: "img1",
    img: "../pic/main1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale!",
    usPrice: "$8.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
    similar: "tshirt",
    section: "Men",
  },
  {
    id: 2,
    subId: 5,
    name: "img1",
    img: "../pic/main2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale!",
    similar: "tshirt",
    section: "Men",
    usPrice: "$9.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
  },
  {
    id: 3,
    subId: 5,
    name: "img2",
    img: "../pic/main3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale!",
    similar: "tshirt",
    section: "Men",
    usPrice: "$7.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
  },
  {
    // similar
    id: 4,
    subId: 5,
    name: "img4",
    img: "../pic/main4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale!",
    similar: "tshirt",
    section: "Men",
    usPrice: "$5.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
  },
  {
    // similar
    id: 4,
    subId: 1,
    name: "img4",
    img: "../pic/submenn5.avif",
    class: "img1",
    similar: "tshirt",
    section: "Men",
    usPrice: "$5.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Hoddies",
    MaxQuantity: 5,
  },
  {
    // similar
    id: 4,
    subId: 1,
    name: "img4",
    img: "../pic/submenn6.avif",
    class: "img1",
    // categoies: "Khmer New Year Sale!",
    similar: "tshirt",
    section: "Men",
    usPrice: "$5.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Hoddies",
    MaxQuantity: 5,
  },
  {
    // similar
    id: 4,
    subId: 1,
    name: "img4",
    img: "../pic/submenn7.avif",
    class: "img1",
    // categoies: "Khmer New Year Sale!",
    similar: "tshirt",
    section: "Men",
    usPrice: "$5.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 5,
  },
  {
    // similar
    id: 4,
    subId: 1,
    name: "img4",
    img: "../pic/submenn8.avif",
    class: "img1",
    // categoies: "Khmer New Year Sale!",
    similar: "tshirt",
    section: "Men",
    usPrice: "$5.99",
    usPriceoff: "$14.95",
    Priceoff: "-40%",
    typeOfShirt: "jacket",
    MaxQuantity: 5,
  },

  // {
  //   name: "img1",
  //   img: "../pic/T-Shirts (10).jpg",
  //   class: "img1",
  //   categoies: "Khmer New Year Sale!",
  // },
  {
    id: 5,
    subId: 22,
    name: "img2",
    img: "../pic/menn2.avif",
    class: "img2",
    categoies: "Khmer New Year Sale1",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 6,
    subId: 22,
    name: "img2",
    img: "../pic/submen1.avif",
    class: "img2",
    categoies: "Khmer New Year Sale1",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 7,
    subId: 22,
    name: "img2",
    img: "../pic/submen2.avif",
    class: "img2",
    categoies: "Khmer New Year Sale1",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 8,
    subId: 22,
    name: "img2",
    img: "../pic/submen3.avif",
    class: "img2",
    categoies: "Khmer New Year Sale1",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 22,
    subId: 5,
    name: "img2",
    img: "../pic/submenn2.avif",
    class: "img2",
    categoies: "Khmer New Year Sale5",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 10,
    subId: 5,
    name: "img1",
    img: "../pic/submenn4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale5",
    usPrice: "$20.99",
    usPriceoff: "$30.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 11,
    subId: 5,
    name: "img1",
    img: "../pic/submenn3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale5",
    usPrice: "$40.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 23,
    subId: 5,
    name: "img1",
    img: "../pic/submenn1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale5",
    usPrice: "$40.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Oversied T-Shirt",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 12,
    subId: 17,
    name: "img1",
    img: "../pic/submenn6.avif",
    class: "img1",
    categoies: "Khmer New Year Sale3",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Hoddies",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 13,
    subId: 17,
    name: "img1",
    img: "../pic/submenn6-1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale3",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Hoddies",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 14,
    subId: 17,
    name: "img1",
    img: "../pic/submenn6-2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale3",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Hoddies",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 15,
    subId: 17,
    name: "img1",
    img: "../pic/submenn6-3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale3",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Hoddies",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 16,
    subId: 17,
    name: "img1",
    img: "../pic/submenn6-4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale3",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Hoddies",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 17,
    subId: 13,
    name: "img1",
    img: "../pic/submenn5.avif",
    class: "img1",
    categoies: "Khmer New Year Sale4",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Hoddies",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 18,
    subId: 13,
    name: "img1",
    img: "../pic/submenn7-1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale4",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Hoddies",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 19,
    subId: 13,
    name: "img1",
    img: "../pic/submenn7-2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale4",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Hoddies",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 20,
    subId: 13,
    name: "img1",
    img: "../pic/submenn7-3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale4",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Hoddies",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 21,
    subId: 13,
    name: "img1",
    img: "../pic/submenn7-4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale4",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Hoddies",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 24,
    subId: 13,
    name: "img1",
    img: "../pic/submenn8.avif",
    class: "img1",
    categoies: "Khmer New Year Sale6",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "jacket",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 25,
    subId: 13,
    name: "img1",
    img: "../pic/submenn8-1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale6",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "jacket",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 26,
    subId: 13,
    name: "img1",
    img: "../pic/submen8-2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale6",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "jacket",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 27,
    subId: 13,
    name: "img1",
    img: "../pic/submenn8-3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale6",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "jacket",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 36,
    subId: 13,
    name: "img1",
    img: "../pic/submenn9.avif",
    class: "img1",
    categoies: "Khmer New Year Sale7",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Hoddies",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 37,
    subId: 13,
    name: "img1",
    img: "../pic/submenn9-1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale7",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Hoddies",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 38,
    subId: 13,
    name: "img1",
    img: "../pic/submenn9-2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale7",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Hoddies",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 39,
    subId: 13,
    name: "img1",
    img: "../pic/submen9-3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale7",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Hoddies",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 40,
    subId: 24,
    name: "img1",
    img: "../pic/submenn10.avif",
    class: "img1",
    categoies: "Khmer New Year Sale8",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "jacket",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 41,
    subId: 24,
    name: "img1",
    img: "../pic/submenn10-1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale8",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "jacket",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 42,
    subId: 24,
    name: "img1",
    img: "../pic/submenn10-2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale8",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "jacket",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 43,
    subId: 24,
    name: "img1",
    img: "../pic/submenn10-3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale8",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "jacket",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 44,
    subId: 24,
    name: "img1",
    img: "../pic/submenn10-3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale8",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "jacket",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    id: 45,
    subId: 24,
    name: "img1",
    img: "../pic/submenn10-4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale8",
    usPrice: "$30.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "jacket",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    // id: 45,
    subId: 24,
    name: "img1",
    img: "../pic/pants1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale8",
    usPrice: "$8.99",
    usPriceoff: "$10.95",
    Priceoff: "-40%",
    typeOfShirt: "Pants And Tights",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    // id: 45,
    subId: 24,
    name: "img1",
    img: "../pic/subpants2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale8",
    usPrice: "$30.99",
    usPriceoff: "$50.95",
    Priceoff: "-40%",
    typeOfShirt: "Pants And Tights",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    // id: 45,
    subId: 24,
    name: "img1",
    img: "../pic/subpants3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale8",
    usPrice: "$20.99",
    usPriceoff: "$40.95",
    Priceoff: "-40%",
    typeOfShirt: "Pants And Tights",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    // id: 45,
    subId: 24,
    name: "img1",
    img: "../pic/subpants1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale8",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Pants And Tights",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    // id: 45,
    subId: 24,
    name: "img1",
    img: "../pic/short.avif",
    class: "img1",
    categoies: "Khmer New Year Sale8",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "short",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    // id: 45,
    subId: 24,
    name: "img1",
    img: "../pic/subshort1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale8",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "short",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    // id: 45,
    subId: 24,
    name: "img1",
    img: "../pic/subshort2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale8",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "short",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    // id: 45,
    subId: 24,
    name: "img1",
    img: "../pic/subshort3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale8",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "short",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    // id: 45,
    subId: 24,
    name: "img1",
    img: "../pic/track.avif",
    class: "img1",
    categoies: "Khmer New Year Sale8",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Tracksuits",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    // id: 45,
    subId: 24,
    name: "img1",
    img: "../pic/subtrack1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale8",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Tracksuits",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    // id: 45,
    subId: 24,
    name: "img1",
    img: "../pic/subtrack2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale8",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Tracksuits",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    // id: 45,
    subId: 24,
    name: "img1",
    img: "../pic/subtrack3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale8",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Tracksuits",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    // id: 45,
    subId: 24,
    name: "img1",
    img: "../pic/subtrack4.avif",
    class: "img1",
    categoies: "Khmer New Year Sale8",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Tracksuits",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    // id: 45,
    subId: 24,
    name: "img1",
    img: "../pic/swim.avif",
    class: "img1",
    categoies: "Khmer New Year Sale8",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Swimwear",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    // id: 45,
    subId: 24,
    name: "img1",
    img: "../pic/subswim1.avif",
    class: "img1",
    categoies: "Khmer New Year Sale8",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Swimwear",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    // id: 45,
    subId: 24,
    name: "img1",
    img: "../pic/subswim2.avif",
    class: "img1",
    categoies: "Khmer New Year Sale8",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Swimwear",
    MaxQuantity: 50,
    similar: "top",
  },
  {
    // id: 45,
    subId: 24,
    name: "img1",
    img: "../pic/subswim3.avif",
    class: "img1",
    categoies: "Khmer New Year Sale8",
    usPrice: "$10.99",
    usPriceoff: "$20.95",
    Priceoff: "-40%",
    typeOfShirt: "Swimwear",
    MaxQuantity: 50,
    similar: "top",
  },

  // Recent Product
  {
    id: 28,
    name: "ASUS Zenbook 14X OLED (UX5401)",
    price: "223$",
    img: "../pic/20240918040216.webp",
    i: "fa fa-star text-primary mr-1",
    iHalf: "fa fa-star-half-alt text-primary mr-1",
    del: "$235.00",
  },
  {
    id: 29,
    name: "ASUS Zenbook 14X OLED (UX5401)",
    price: "123$",
    img: "../pic/20240918040216.webp",
    i: "fa fa-star text-primary mr-1",
    iHalf: "fa fa-star-half-alt text-primary mr-1",
    del: "$125.00",
  },
  {
    id: 30,
    name: "ASUS Zenbook 14X OLED (UX5401)",
    price: "300$",
    img: "../pic/20240918040216.webp",
    i: "fa fa-star text-primary mr-1",
    iHalf: "fa fa-star-half-alt text-primary mr-1",
    del: "$335.00",
  },
  {
    id: 31,
    name: "ASUS Zenbook 14X OLED (UX5401)",
    price: "$234",
    img: "../pic/20240918040216.webp",
    i: "fa fa-star text-primary mr-1",
    iHalf: "fa fa-star-half-alt text-primary mr-1",
    del: "$255.00",
  },
  {
    id: 32,
    name: "ASUS Zenbook 14X OLED (UX5401)",
    price: "$234",
    img: "../pic/20240918040216.webp",
    i: "fa fa-star text-primary mr-1",
    iHalf: "fa fa-star-half-alt text-primary mr-1",
    del: "$255.00",
  },
  {
    id: 33,
    name: "ASUS Zenbook 14X OLED (UX5401)",
    price: "$234",
    img: "../pic/20240918040216.webp",
    i: "fa fa-star text-primary mr-1",
    iHalf: "fa fa-star-half-alt text-primary mr-1",
    del: "$255.00",
  },
  {
    id: 34,
    name: "ASUS Zenbook 14X OLED (UX5401)",
    price: "$234",
    img: "../pic/20240918040216.webp",
    i: "fa fa-star text-primary mr-1",
    iHalf: "fa fa-star-half-alt text-primary mr-1",
    del: "$255.00",
  },
  {
    id: 35,
    name: "ASUS Zenbook 14X OLED (UX5401)",
    price: "$234",
    img: "../pic/20240918040216.webp",
    i: "fa fa-star text-primary mr-1",
    iHalf: "fa fa-star-half-alt text-primary mr-1",
    del: "$255.00",
  },
];
const wrappersimilar = document.querySelector(".wrapper-similar");
// wrappersimilar.innerHTML = dataSmall
//   .filter((e) => {
//     return e.section == "Men";
//   })
//   .map((a) => {
//     return `
//             <div class="col-lg-4 mb-4 col-6">
//                 <div class="image-card-wrapper w-100 overflow-hidden">
//                     <a href="data.html?id=${a.id}">
//                         <img src="${a.img}" class="${a.class}" alt="${a.name}">
//                     </a>
//                 </div>
//                 <div class="wrapper-similar-text mt-3 overflow-hidden">
//                     <div class="wrapper-hover">
//                     <div class="wrapper-flex-text d-flex justify-content-between align-items-center ">
//                         <h5 class="fw-bold text-dark m-0 price-text">US ${a.usPrice}</h5>
//         <h5 class=" text-dark fw-bolder clickFav" id="offcanvasRightLabel"><i class="fa-regular fa-heart clickHeart"></i>
//         </h5>
//     </div>
//     <span class="offPriceShow">${a.usPriceoff}</span>
//                                     <div class="flex-img d-flex justify-content-between align-items-center">
//                                     <p class="fw-light pt-1 mb-0">${a.typeOfShirt}</p>
//                                     <a href="data.html?id=${a.id}">
//                         <img src="${a.img}" class="${a.class} img-price" alt="${a.name}" style="width:35px;height: 35px;">
//                     </a>
//                 </div>
//                 </div>
//                 </div>
//             </div>
//           `;
//   })
//   .join("");

//   btn-filter
const ul = document.querySelector(".clothes-flters");
const li = document.querySelectorAll(".custom-cursor-on-hover");
const displayItems = (items) => {
  const showing = items
    .map((a) => {
      return `
 <div class="col-lg-4 mb-4 col-6 " data-aos="zoom-in-up">
                <div class="image-card-wrapper w-100 overflow-hidden">
                    <a href="data.html?id=${a.id}">
                        <img src="${a.img}" class="${a.class}" alt="${a.name}">
                    </a>
                </div>
                <div class="wrapper-similar-text mt-3 overflow-hidden">
                    <div class="wrapper-hover">
                    <div class="wrapper-flex-text d-flex justify-content-between align-items-center ">
                        <h5 class="fw-bold text-dark m-0 price-text">US ${a.usPrice}</h5>
        <h5 class=" text-dark fw-bolder clickFav" id="offcanvasRightLabel"><i class="fa-regular fa-heart clickHeart"></i>
        </h5>
    </div>
    <span class="offPriceShow">${a.usPriceoff}</span>
                                    <div class="flex-img d-flex justify-content-between align-items-center"> 
                                    <p class="fw-light pt-1 mb-0">${a.typeOfShirt}</p>
                                    <a href="data.html?id=${a.id}">
                        <img src="${a.img}" class="${a.class} img-price" alt="${a.name}" style="width:35px;height: 35px;">
                    </a>
                </div>
                </div>
                </div>
            </div>
      </div>
      `;
    })
    .join("");
  wrappersimilar.innerHTML = showing;
};

window.addEventListener("DOMContentLoaded", () => {
  displayItems(dataSmall.filter((item) => item.id < 50));
});

li.forEach((item) => {
  item.addEventListener("click", (e) => {
    const categories = e.target.dataset.id;
    const newdata = dataSmall.filter((item) => item.typeOfShirt === categories);

    if (categories === "all") {
      displayItems(dataSmall.filter((item) => item.id < 50));
    } else {
      displayItems(newdata);
    }
  });
});
li.forEach((item) => {
  item.addEventListener("click", (e) => {
    li.forEach((el) => el.classList.remove("active"));
    e.target.classList.add("active");

    const categories = e.target.dataset.id;
    const newdata = dataSmall.filter((item) => item.typeOfShirt === categories);

    if (categories === "all") {
      displayItems(dataSmall.filter((item) => item.id < 16));
    } else {
      displayItems(newdata);
    }
  });
});
